# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    #    resolvers:
    #        default:
    #            web_path: ~
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [253, 253], mode: outbound}
        details:
            quality: 90
            filters:
                thumbnail: { size: [350, 437.5], mode: outbound }
        home:
            quality: 90
            filters:
                thumbnail: { size: [1265, 350], mode: outbound }
